local cocos2d_base = {}

cocos2d_base.src = {
	"cocos/base/CCAsyncTaskPool.*",
	"cocos/base/CCAutoreleasePool.*",
	"cocos/base/CCConfiguration.*",
	"cocos/base/CCConsole.*",
	"cocos/base/CCController.*",
	"cocos/base/CCData.*",
	"cocos/base/CCDataVisitor.*",
	"cocos/base/CCNinePatchImageParser.*",
	"cocos/base/CCDirector.*",
	"cocos/base/CCEvent.*",
	"cocos/base/CCEventAcceleration.*",
	"cocos/base/CCEventController.*",
	"cocos/base/CCEventCustom.*",
	"cocos/base/CCEventDispatcher.*",
	"cocos/base/CCEventFocus.*",
	"cocos/base/CCEventKeyboard.*",
	"cocos/base/CCEventListener.*",
	"cocos/base/CCEventListenerAcceleration.*",
	"cocos/base/CCEventListenerController.*",
	"cocos/base/CCEventListenerCustom.*",
	"cocos/base/CCEventListenerFocus.*",
	"cocos/base/CCEventListenerKeyboard.*",
	"cocos/base/CCEventListenerMouse.*",
	"cocos/base/CCEventListenerTouch.*",
	"cocos/base/CCEventMouse.*",
	"cocos/base/CCEventTouch.*",
	"cocos/base/CCIMEDispatcher.*",
	"cocos/base/CCNS.*",
	"cocos/base/CCProfiling.*",
	"cocos/base/CCProperties.*",
	"cocos/base/CCRef.*",
	"cocos/base/CCScheduler.*",
	"cocos/base/CCScriptSupport.*",
	"cocos/base/CCTouch.*",
	"cocos/base/CCUserDefault.*",
	"cocos/base/CCValue.*",
	"cocos/base/ObjectFactory.*",
	"cocos/base/CCStencilStateManager.*",
	"cocos/base/TGAlib.*",
	"cocos/base/ZipUtils.*",
	"cocos/base/allocator/CCAllocatorDiagnostics.*",
	"cocos/base/allocator/CCAllocatorGlobal.*",
	"cocos/base/allocator/CCAllocatorGlobalNewDelete.*",
	"cocos/base/atitc.*",
	"cocos/base/base64.*",
	"cocos/base/ccCArray.*",
	"cocos/base/ccFPSImages.*",
	"cocos/base/ccRandom.*",
	"cocos/base/ccTypes.*",
	"cocos/base/ccUTF8.*",
	"cocos/base/ccUtils.*",
	"cocos/base/etc1.*",
	"cocos/base/pvr.*",
	"cocos/base/s3tc.*",
  
}

return cocos2d_base