local ui = {}

ui.src = {
"cocos/ui/UIEditBox/UIEditBoxImpl-win32.*",
"cocos/ui/CocosGUI.*",
"cocos/ui/UIButton.*",
"cocos/ui/UIAbstractCheckButton.*",
"cocos/ui/UICheckBox.*",
"cocos/ui/UIRadioButton.*",
"cocos/ui/UIDeprecated.*",
"cocos/ui/UIHBox.*",
"cocos/ui/UIHelper.*",
"cocos/ui/UIImageView.*",
"cocos/ui/UILayout.*",
"cocos/ui/UILayoutManager.*",
"cocos/ui/UILayoutParameter.*",
"cocos/ui/UIListView.*",
"cocos/ui/UILoadingBar.*",
"cocos/ui/UIPageView.*",
"cocos/ui/UIPageViewIndicator.*",
"cocos/ui/UIRelativeBox.*",
"cocos/ui/UIRichText.*",
"cocos/ui/UIScale9Sprite.*",
"cocos/ui/UIScrollView.*",
"cocos/ui/UIScrollViewBar.*",
"cocos/ui/UISlider.*",
"cocos/ui/UIText.*",
"cocos/ui/UITextAtlas.*",
"cocos/ui/UITextBMFont.*",
"cocos/ui/UITextField.*",
"cocos/ui/UIVBox.*",
"cocos/ui/UIWebView.*",
"cocos/ui/UIWidget.*",
"cocos/ui/UIEditBox/UIEditBox.*",
"cocos/ui/UILayoutComponent.*",
"cocos/ui/UIEditBox/UIEditBoxImpl-common.*",
"cocos/ui/UITabControl.*",
}

return ui